# Generated by Django 4.0 on 2021-12-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentify', '0003_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
