# Generated by Django 3.2.9 on 2021-12-01 11:45

from django.db import migrations, models
import learning.models.structure
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.IntegerField(unique=True, validators=[learning.models.structure.validate_level])),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
