# Generated by Django 4.0 on 2021-12-13 23:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentify', '0004_alter_user_email'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('content', models.FileField(upload_to='resources')),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=128)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.level')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentify.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
